# Generated by Django 3.2.4 on 2021-06-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('dirección_cliente', models.CharField(max_length=150)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('numero_despacho', models.CharField(max_length=30, unique=True)),
                ('productos_cliente', models.TextField()),
                ('peso_productos', models.PositiveIntegerField()),
                ('fecha_ingreso_despacho', models.DateField()),
                ('fecha_envio_despacho', models.DateField()),
                ('estado_despacho', models.CharField(choices=[('por enviar', 'Por Enviar'), ('entregado', 'Entregado')], default='Por Enviar', max_length=50)),
                ('profundidad_despacho', models.PositiveIntegerField()),
                ('ancho_despacho', models.PositiveIntegerField()),
                ('alto_despacho', models.PositiveIntegerField()),
            ],
        ),
    ]
